---
- name: Set database to internal or external
  set_fact:
    config_dynamic_database: "{{ ( (pg_host is not defined or pg_host == '') or (pg_host | match('/.*')) ) | ternary('internal', 'external') }}"

- name: Database decision
  debug: var=config_dynamic_database

- name: Set postgres host and port to local if not set
  set_fact:
    pg_host: '127.0.0.1'
    pg_port: 5432
  when: "pg_host is not defined or pg_host == ''"